- name: install epel
  yum:
    name: epel-release
    state: present
 
- name: dowload zabbix rpm
  get_url:
      url: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
      dest: /tmp/zabbix-release-4.0-1.el7.noarch.rpm
      mode: '0440'
      validate_certs: no

- name: install package rpm
  yum:
    name: /tmp/zabbix-release-4.0-1.el7.noarch.rpm
    state: present      

- name: update all packages  system
  yum:
    name: '*'
    update_cache: yes
    state: latest    

- name: clean cache
  command: yum clean all     
  